remote: true
hybrid: true
onsite: false

experienceLevel:
  internship: true
  entry: true
  associate: false
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: true
  other: false
  volunteer: false

date:
  all time: false
  month: True
  week: True
  24 hours: false

positions:
  - Software engineer

locations:
  - India

apply_once_at_company: true

distance: 200

company_blacklist:
  - wayfair
  - Crossover

title_blacklist:
  - word1
  - word2

location_blacklist:
  - china

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 1500

llm_model_type: geminigenai.GenerativeModel
llm_model: "gemini-1.5-flash"
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'
